openapi: 3.0.3
info:
  title: Gallerio API
  version: 0.1.0
paths:
  /api/health:
    get:
      summary: Health
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties: { ok: { type: boolean } }

